apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: directvolumemigrationprogresses.migration.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.clusterRef.name
    name: Cluster
    type: string
  - JSONPath: .spec.podRef.name
    name: PodName
    type: string
  - JSONPath: .spec.podRef.Namespace
    name: PodNamespace
    type: string
  - JSONPath: .status.lastObservedProgressPercent
    name: ProgressPercent
    type: string
  - JSONPath: .status.lastObservedTransferRate
    name: TransferRate
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: string
  group: migration.openshift.io
  names:
    kind: DirectVolumeMigrationProgress
    plural: directvolumemigrationprogresses
    shortNames:
    - dvmp
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterRef:
              type: object
            podRef:
              type: object
          type: object
        status:
          properties:
            lastObservedProgressPercent:
              type: string
            lastObservedTransferRate:
              type: string
            logMessage:
              type: string
            observedDigest:
              type: string
            phase:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
