apiVersion: migration.openshift.io/v1alpha1
kind: DirectVolumeMigrationProgress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: directvolumemigrationprogress-sample
spec:
  clusterRef:
    name: sample-source-3110
    namespace: openshift-migration
  podRef:
    name: directmigration-sample-pod-0
    namespace: openshift-migration