apiVersion: migration.openshift.io/v1alpha1
kind: DirectVolumeMigrationProgress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: directvolumemigrationprogress-sample
spec:
  # [!] Change clusterRef to point to the cluster where the pod is running
  clusterRef:
    name: sample-source-3110
    namespace: openshift-migration
  # [!] Change podRef to point to the name and namespace of the running pod
  podRef:
    name: directmigration-sample-pod-0
    namespace: openshift-migration